
# Useful commands:
# docker-compose build
# docker-compose up
# docker-compose ps
# docker compose stop
# docker-compose down

version: '3.7'

services:
  api:
    build:
      context: ''
      dockerfile: Dockerfile
    environment:
      REDIS_PORT: 6379
      DATABASE_URL: postgres://admin:admin@postgres:5432/local
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: local
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432