
# Useful commands:
# docker-compose build
# docker-compose up
# docker-compose ps
# docker compose stop
# docker-compose down

version: '3.7'

services:
  api:
    build:
      context: ''
      dockerfile: Dockerfile
    environment:
      REDIS_PORT: 6379
      DATABASE_URL: postgres://postgres@postgres/
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: local
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379